name: 'Virtual AI Developer'
description: 'Automates routine tasks in software development'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
