name:  Master Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Unit-Tests
      run: |
        export PATH=$(pwd)/bin:$PATH
        export PYTHONPATH=$(pwd)/bin:${PYTHONPATH}
        python -m coverage run -m pytest tests/unit

    - name: Fail if coverage is less than 80%
      run: |
        coverage report --fail-under=80

    - name: Integration Tests
      run: |
        export PATH=$(pwd)/bin:$PATH
        export PYTHONPATH=$(pwd)/bin:${PYTHONPATH}
        python -m pytest tests/integration/hallux_fix_test.py

#    - name: Run Hallux
#      run: python ./worker/main.py
#      env:
#        GITHUB_TOKEN: ${{ secrets.HALLUX_GITHUB_TOKEN }}
#        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#        OPENAI_MODEL: text-davinci-003
#        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
