name:  Hallux pipeline

on:
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run Hallux
      run: python ./worker/main.py
      # uses: halluxai/hallux@feature/integrate-with-github-api
      # with:
      #   github-token: ${{ secrets.GITHUB_TOKEN }}
      #   pull-request-number: ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: text-davinci-003
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
