name: Master Pipeline

on:
  push:
    branches: [ 71-split-pr-pipeline ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    # - name: Unit-Tests
    #   run: |
    #     export PATH=$(pwd)/bin:$PATH
    #     export PYTHONPATH=$(pwd)/hallux:${PYTHONPATH}
    #     ./scripts/set-version.sh

    #     python -m pytest \
    #       --cov-branch \
    #       --cov-report=term \
    #       --cov=hallux \
    #       --cov-report=xml \
    #       --cov-fail-under=65 \
    #       --junitxml xunit-reports/xunit-result-unit.xml \
    #       tests/unit \
    #       tests/integration/hallux_fix_test.py

    # - uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     SONAR_PROJECT_VERSION: ${{ github.run_number }}


    - name: Try to fix Sonar issues
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_VERSION: ${{ github.run_number }}
        GITHUB_TOKEN: ${{ secrets.HALLUX_GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CURRENT_BRANCH: ${{ github.ref_name }}
      run: |

        export PYTHONPATH=$(pwd):${PYTHONPATH}

        # 1. create new branch:
        formatted_date=$(date "+%Y-%m-%d")
        branch_name=hallux_${formatted_date}_$(git rev-parse --short HEAD)
        git checkout -b $branch_name

        # 2. run hallux
        # LOG_LEVEL=DEBUG python3 ./hallux/main.py --sonar --gpt3 --git hallux

        # Configure git
        git config --global user.email "team@hallux.dev"
        git config --global user.name "Hallux AI Developer"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/halluxdev/hallux.git

        git status

        git push origin $branch_name

        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/halluxdev/hallux/pulls \
          -d '{"title":"Hallux improvements ${formatted_date}","body":"Please review","head":"octocat:new-feature","base":"${CURRENT_BRANCH}"}'


        #     --filter sonar issues
        #     --time of the issue
        # 3. collect fixing statistics, success/unsuccess ratio
        # 3. if any fixes push branch and create PR with possible fix


