name: Python CI

on: [push, pull_request]

env:
  PYTHONPATH: ${{ github.workspace }}/bin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run integration tests with coverage
      run: |
        pwd
        ls -la
        export PATH=$(pwd)/bin:$PATH
        echo $PATH
        PYTHONPATH=(pwd)/bin coverage run -m pytest tests/integration/hallux_fix_test.py

    - name: Fail if coverage is less than 50%
      run: |
        coverage report --fail-under=50
